#!/bin/bash

# This file is executed when a newly created container
# is started. Use it to perform initial container setup
# actions, such as configuring dotfiles.

cat << 'EOF'
╔══════════════════════════════════════════════════════════════╗
║                   Theos 22.04 Dev Container                 ║
║                                                              ║
║  Theos: $THEOS/theos                                         ║
║  SDKs:  $THEOS/sdks                                          ║
║  Work:  ~/work                                               ║
║                                                              ║
║  Start a new tweak project:                                  ║
║    $ nic.pl                                                  ║
╚══════════════════════════════════════════════════════════════╝
EOF

# ln -sf ~/work/.bashrc ~/.bashrc
# ln -sf ~/work/.gitconfig ~/.gitconfig
# ln -sf ~/work/.ssh ~/.ssh
