services:
  theos:
    build:
      context: .
      args:
        - CHANGE_SOURCE=false
    image: theos:22.04
    container_name: theos
    volumes:
      - theos-data:/home/me/theos:Z
      - theos-work:/home/me/work:Z
    stdin_open: true
    tty: true
volumes:
  theos-data:
  theos-work:
